name: Scrape Install Count

on:
  schedule:
    - cron: '0 0 * * *' # 每天北京时间08:00运行一次

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 matplotlib

      - name: Run scraper
        run: python .github/scripts/scraper.py

      - name: Generate graph
        run: python .github/scripts/generate_graph.py

      - name: Commit and push data
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add install_counts.json install_count.png
          git commit -m "Update install count and graph"
          git push

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo '![Install Count](install_count.png)' > README.md
          git add README.md
          git commit -m "Update README with new graph"
          git push
